### ISSUE TITLE
Remove "workshop 1" from the title

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/ws-password-management#13]
For [composability of workshops & ordering in a curriculum](https://github.com/foundersandcoders/master-reference/blob/master/vision.md#implementation), we prob shouldn't specify that this is the 1st workshop directly in the readme

**Comment by ronanyeah** [comment]
https://github.com/foundersandcoders/ws-password-management/commit/2cfc231bd6ddb97eb4a9316c67020f3e316d334f
