### ISSUE TITLE
change tests from jest to tape?

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/ws-password-management#17]
It's probably not a good idea to have files in our workshops that make us say things to the students like "don't worry, you don't need to understand this".

At first, I didn't think that using a different framework than the one that is taught on the course was much of a problem. But it does make the workshop slightly more difficult for students and mentors to contribute to - see issue #16 

It also stops us from putting any extra steps in the workshop that require students to write their own tests (without learning about Jest first) #7 & it's clear that this workshop needs to be longer, in order to fit the time slot https://github.com/foundersandcoders/master-reference/issues/550

**Comment by matthewdking** [comment]
I have made a [PR](https://github.com/foundersandcoders/ws-password-management/pull/18) request for this

**Comment by eliasmalik** [comment]
Closed by #18
