### ISSUE TITLE
Unexplained presence of dotenv module

### ISSUE THREAD

**Issue by maxgerber** [foundersandcoders/ws-password-management#23]
Someone from FAC12 just flagged up the presence of a dotenv file in ```index.test.js```. As far as we can work out, it does a similar thing to env2 - but we couldn't work out a feasible scenario we would use it in. @ronanyeah can you comment - is there a way we could make this explicit as an extension in the workshop? Or alternatively, does it need to be there at all?

**Comment by ronanyeah** [comment]
Yeah it should be removed, I'll do it this evening.

**Comment by maxgerber** [comment]
Cheers!
