### ISSUE TITLE
needs solution folder

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/ws-password-management#3]
Following the pattern set out in all other morning challenges and workshops, it would be good to have a solutions folder.

Based on the gitter conversations, I am assuming we're going with a callbacks instead of promises?

**Comment by ronanyeah** [comment]
@jsms90 https://github.com/foundersandcoders/ws-password-management/issues/2#issuecomment-319505061

**Comment by ronanyeah** [comment]
I'll add solutions at the same time.
