### ISSUE TITLE
more detailed learning outcomes

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/ws-password-management#5]
It reckon it helps to be really clear about what we want students to understand and be able to do after completing a workshop.

The following suggestions are mostly based on the existing material in the workshop, but also the suggested addition of a database (see issue #6 ).

Understand:
+ the importance of making passwords non-recoverable from a database
+ the difference between encrypting and hashing
+ why a password should be hashed before being stored
+ which hashing algorithms should be used and why
+ what a salt is and how it helps to protect against lookup table and rainbow table attacks
+ how salts should be generated and used
+ how a cryptographic hash function minimises vulnerability to brute force and dictionary attacks
+ what bcrypt is doing under the hood i.e. key stretching, iteration count

Be able to implement the following:
+ generate a random salt (using bcrypt.js)
+ hash a password (using bcrypt.js)
+ store this in a database
+ retrieve the hashed password from the database
+ compare it (using bcrypt.js) to the user input

**Comment by ronanyeah** [comment]
@jsms90 I think something like this is better to be a pull request. Also I disagree with adding a database to the workshop. They will be doing that in the project and they won't be learning anything new from it (they've already done SQL week), so why is it in this workshop?

**Comment by jsms90** [comment]
@ronanyeah Yeah fair enough! I figured it might need discussion before being ready for a PR, just in case I'm misunderstanding any of these concepts myself :woman_shrugging: or in case you disagreed with the issue itself.
