### ISSUE TITLE
add a database to this workshop

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/ws-password-management#6]
If we had a database, we could ask students to store the password (after using bycrpt to hash it). Then we could also get students to retrieve it from the database & compare it to an example user input.

Since we have postgres week right before authentication week, having a database would:
+ help to link this workshop to the week's project
+ provide real-world context to students when they're writing the hashing and comparison functions
+ be a nice segway between weeks and consolidation of concepts from the week before

What do you reckon @ronanyeah @des-des @alexis-l8 @bo-bok?

**Comment by jsms90** [comment]
@ronanyeah 
> I disagree with adding a database to the workshop. They will be doing that in the project and they won't be learning anything new from it (they've already done SQL week), so why is it in this workshop?

Yeah I do see what you mean. We definitely don't want to do all the work for them, that they're supposed to do in the project! But as you've said, they should have learned these concepts last week. After all, the aim of this week's project is to implement authentication.

I reckon we should treat the fact that they can query their database from their handlers as a given. So the energy they expend during project time should be focused on how to implement the new concepts i.e. authentication itself.

AND they're way more likely to learn and truly understand the need to hash a password, if the workshop shows how that relates to storing the password. Likewise, it makes more sense to be writing a comparison function, when you have 2 passwords to compare to each other. It makes it slightly harder to grasp the value of what they're being asked to do, when the context is removed.

**Comment by ronanyeah** [comment]
@jsms90 It's a hashing workshop. They'll be using DB's in the project. I'm a hard no on this for many reasons.

**Comment by des-des** [comment]
@jsms90 yeah for the same reason I think promises are a bad idea, I think the focus should be on the main learning points of this workshop .. So yeah I think setting up db etc would be a distraction

**Comment by jsms90** [comment]
@ronanyeah @des-des To clarify, I'm not suggesting that we get students to set up a database as part of this workshop. That would definitely be a distraction from the learning outcomes & a waste of time since they've already learned that last week.

I'm suggesting that we have a database already set up in this repo, so that the students see how this fits into the context of what they already know. (See issue #7 for how this fits in to making this more of a workshop than a readme)
