### ISSUE TITLE
Missing explainations of key terms / terms that might need more explanation

### ISSUE THREAD

**Issue by des-des** [foundersandcoders/ws-password-management#9]
- [ ] brute force
 - [ ] `escalation of a read only attack`
 - [ ] `This number is logarithmic so the execution time increases quite sharply`. is it just the the execution time increases exponentially? Kinda the same, either way not sure students will know what the word logarithmic means

**Comment by ronanyeah** [comment]
https://github.com/foundersandcoders/ws-password-management/issues/4#issuecomment-320523457
